'use strict';
/**
 * Restore manifests. Before Hangar kills anything, it writes a manifest
 * recording exactly what is about to die and how to bring it back. The write
 * happens BEFORE the kill — if the manifest can't be written, nothing dies.
 *
 * Restore is honest about its limits: we can relaunch a recorded command
 * line, but we cannot restore in-memory state. The UI labels it best-effort.
 */

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const { spawn } = require('child_process');

const DIR = path.join(__dirname, '..', 'manifests');

/**
 * OS-managed helpers that get swept up by tree expansion but must never be
 * relaunched. conhost is the console host Windows attaches to a console
 * process — its command line is an NT-namespace path with a handle argument
 * (`\??\C:\Windows\system32\conhost.exe 0x4`), meaningless outside the
 * original session. It respawns on its own when the real process returns.
 */
const NON_RESTORABLE = [/^conhost\.exe$/i, /^dllhost\.exe$/i, /^RuntimeBroker\.exe$/i];

function isRestorable(v) {
  if (NON_RESTORABLE.some((re) => re.test(v.name || ''))) return false;
  if (!v.path && !v.cmd) return false;
  // NT-namespace or device paths cannot be respawned as-is.
  if (v.cmd && /^\\\?\?\\/.test(v.cmd.trim())) return false;
  return true;
}

/**
 * Split a Windows command line into argv, honouring double-quoted segments.
 * We spawn the executable directly with this argv rather than going through
 * `cmd /c`: cmd strips the first and last quote of a quoted command, which
 * silently corrupts any path containing spaces.
 */
function splitArgv(cmdline) {
  const out = [];
  let cur = '';
  let inQuote = false;
  let has = false;
  for (const ch of String(cmdline)) {
    if (ch === '"') { inQuote = !inQuote; has = true; continue; }
    if (!inQuote && /\s/.test(ch)) {
      if (has || cur) { out.push(cur); cur = ''; has = false; }
      continue;
    }
    cur += ch;
  }
  if (has || cur) out.push(cur);
  return out.filter((s) => s.length);
}

function ensureDir() {
  fs.mkdirSync(DIR, { recursive: true });
}

/**
 * Write a manifest for a set of processes about to be parked.
 * Throws on failure — callers must treat a failed write as "do not kill".
 */
function writeManifest(action, victims, meta = {}) {
  ensureDir();
  const id = `${new Date().toISOString().replace(/[:.]/g, '-')}_${crypto.randomBytes(3).toString('hex')}`;
  const manifest = {
    id,
    action,                       // 'park' | 'kill'
    at: new Date().toISOString(),
    meta,                         // { confirmPhrase, requestedPids, note }
    victims: victims.map((v) => ({
      pid: v.pid,
      name: v.name,
      memMB: v.memMB ?? null,
      cmd: v.cmd ?? null,
      path: v.path ?? null,
      ports: v.ports ?? [],
      // Persistence victims are not processes — they carry the literal action
      // (from/to paths, registry value, task name) needed to invert the change.
      // Without this the manifest records only prose and cannot be undone.
      persistence: v.persistence ?? null,
      restorable: v.persistence ? true : isRestorable(v),
    })),
    restored: null,               // set by markRestored
  };
  const file = path.join(DIR, `${id}.json`);
  fs.writeFileSync(file, JSON.stringify(manifest, null, 2), { flag: 'wx' });
  return manifest;
}

function listManifests() {
  ensureDir();
  return fs.readdirSync(DIR)
    .filter((f) => f.endsWith('.json'))
    .map((f) => {
      try { return JSON.parse(fs.readFileSync(path.join(DIR, f), 'utf8')); }
      catch { return null; }
    })
    .filter(Boolean)
    .sort((a, b) => b.at.localeCompare(a.at));
}

function getManifest(id) {
  // ids are generated by us; reject anything path-shaped
  if (!/^[\w\-]+$/.test(id)) return null;
  const file = path.join(DIR, `${id}.json`);
  try { return JSON.parse(fs.readFileSync(file, 'utf8')); }
  catch { return null; }
}

/** Record the outcome of a restore performed by an external executor. */
function markRestored(id, results) {
  const m = getManifest(id);
  if (!m) return null;
  m.restored = { at: new Date().toISOString(), results };
  fs.writeFileSync(path.join(DIR, `${id}.json`), JSON.stringify(m, null, 2));
  return m;
}

/**
 * Best-effort restore: relaunch each victim's recorded command, detached.
 * Returns per-victim results; never throws for a single failed relaunch.
 */
function restoreManifest(id) {
  const m = getManifest(id);
  if (!m) return { ok: false, error: 'manifest not found' };

  // Persistence manifests are undone by inverting their recorded actions, not
  // by spawning processes. The caller (server.js) owns the PowerShell executor,
  // so surface the inverse actions and let it run them.
  if (/^persist-/.test(m.action || '')) {
    return { ok: false, needsPersistenceExecutor: true, manifest: m };
  }

  const results = [];
  for (const v of m.victims) {
    if (!v.restorable) {
      results.push({
        pid: v.pid, name: v.name, ok: false,
        why: NON_RESTORABLE.some((re) => re.test(v.name || ''))
          ? 'OS-managed helper — respawns on its own, nothing to restore'
          : 'no usable path or command was recorded',
      });
      continue;
    }
    try {
      // Spawn the executable directly. Going through `cmd /c` mangles quoted
      // paths (cmd strips the outer quote pair), which is why the first
      // restore reported success while nothing actually came back.
      const argv = splitArgv(v.cmd || '');
      const exe = v.path || argv[0];
      const args = v.path && argv.length && argv[0].toLowerCase().includes(path.basename(v.path).toLowerCase())
        ? argv.slice(1)
        : argv.slice(1);
      if (!exe) throw new Error('no executable resolved');

      const child = spawn(exe, args, {
        detached: true,
        stdio: 'ignore',
        windowsHide: false,
        cwd: path.dirname(exe),
      });
      child.unref();
      results.push({
        pid: v.pid, name: v.name, ok: true,
        relaunched: [exe, ...args].join(' ').slice(0, 160),
        newPid: child.pid ?? null,
      });
    } catch (e) {
      results.push({ pid: v.pid, name: v.name, ok: false, why: e.message });
    }
  }

  m.restored = { at: new Date().toISOString(), results };
  fs.writeFileSync(path.join(DIR, `${id}.json`), JSON.stringify(m, null, 2));
  return { ok: true, results };
}

module.exports = {
  writeManifest, listManifests, getManifest, restoreManifest, markRestored,
  __test: { splitArgv, isRestorable },
};
