//! Restore manifests — Rust port of `lib/manifest.js`.
//!
//! The manifest is written BEFORE anything is killed or changed. If the write
//! fails, nothing happens. That ordering is the whole safety story: on this
//! machine a persistence change once produced a manifest containing only prose
//! ("Move Facebook.lnk out of Startup into quarantine") because the action
//! object was dropped, and the undo button became fiction. The `persistence`
//! field below is what makes an undo actually executable.

use crate::persistence::Action;
use serde::{Deserialize, Serialize};
use std::fs;
use std::path::{Path, PathBuf};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Victim {
    #[serde(default)]
    pub pid: Option<u32>,
    pub name: String,
    #[serde(default, rename = "memMB")]
    pub mem_mb: Option<f64>,
    #[serde(default)]
    pub cmd: Option<String>,
    #[serde(default)]
    pub path: Option<String>,
    #[serde(default)]
    pub ports: Vec<u16>,
    /// Present only for persistence manifests. Carries the literal action so
    /// the change can be inverted with no live entry available.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub persistence: Option<Action>,
    pub restorable: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Manifest {
    pub id: String,
    pub action: String,
    pub at: String,
    #[serde(default)]
    pub meta: serde_json::Value,
    pub victims: Vec<Victim>,
    #[serde(default)]
    pub restored: Option<serde_json::Value>,
}

/// OS-managed helpers that get swept up by tree expansion but must never be
/// relaunched. conhost's command line is an NT-namespace path with a handle
/// argument, meaningless outside the original session.
fn non_restorable(name: &str) -> bool {
    matches!(
        name.to_ascii_lowercase().as_str(),
        "conhost.exe" | "dllhost.exe" | "runtimebroker.exe"
    )
}

pub fn is_restorable(name: &str, path: &Option<String>, cmd: &Option<String>) -> bool {
    if non_restorable(name) {
        return false;
    }
    if path.is_none() && cmd.is_none() {
        return false;
    }
    // NT-namespace paths cannot be respawned as-is.
    if cmd.as_deref().map(|c| c.trim_start().starts_with(r"\??\")).unwrap_or(false) {
        return false;
    }
    true
}

/// Split a Windows command line into argv, honouring double-quoted segments.
///
/// We spawn the executable directly with this argv rather than going through
/// `cmd /c`: cmd strips the outer quote pair, which silently corrupts any path
/// containing spaces. That bug made a restore report success while nothing
/// came back.
pub fn split_argv(cmdline: &str) -> Vec<String> {
    let mut out = Vec::new();
    let mut cur = String::new();
    let mut in_quote = false;
    let mut has = false;
    for ch in cmdline.chars() {
        match ch {
            '"' => {
                in_quote = !in_quote;
                has = true;
            }
            c if c.is_whitespace() && !in_quote => {
                if has || !cur.is_empty() {
                    out.push(std::mem::take(&mut cur));
                    has = false;
                }
            }
            c => cur.push(c),
        }
    }
    if has || !cur.is_empty() {
        out.push(cur);
    }
    out.retain(|s| !s.is_empty());
    out
}

pub struct Store {
    dir: PathBuf,
}

impl Store {
    pub fn new(dir: impl AsRef<Path>) -> Self {
        Self { dir: dir.as_ref().to_path_buf() }
    }

    fn ensure(&self) -> std::io::Result<()> {
        fs::create_dir_all(&self.dir)
    }

    /// Write a manifest. Callers MUST treat a failure here as "do not proceed".
    pub fn write(
        &self,
        action: &str,
        victims: Vec<Victim>,
        meta: serde_json::Value,
    ) -> std::io::Result<Manifest> {
        self.ensure()?;
        let id = format!("{}_{:06x}", now_stamp(), rand_suffix());
        let m = Manifest {
            id: id.clone(),
            action: action.to_string(),
            at: now_iso(),
            meta,
            victims,
            restored: None,
        };
        let file = self.dir.join(format!("{id}.json"));
        fs::write(&file, serde_json::to_string_pretty(&m)?)?;
        Ok(m)
    }

    pub fn list(&self) -> Vec<Manifest> {
        let Ok(rd) = fs::read_dir(&self.dir) else { return Vec::new() };
        let mut out: Vec<Manifest> = rd
            .filter_map(|e| e.ok())
            .filter(|e| e.path().extension().is_some_and(|x| x == "json"))
            .filter_map(|e| fs::read_to_string(e.path()).ok())
            .filter_map(|s| serde_json::from_str(&s).ok())
            .collect();
        out.sort_by(|a, b| b.at.cmp(&a.at));
        out
    }

    pub fn get(&self, id: &str) -> Option<Manifest> {
        // ids are generated by us; reject anything path-shaped
        if !id.chars().all(|c| c.is_ascii_alphanumeric() || c == '-' || c == '_') {
            return None;
        }
        let s = fs::read_to_string(self.dir.join(format!("{id}.json"))).ok()?;
        serde_json::from_str(&s).ok()
    }

    pub fn mark_restored(&self, id: &str, results: serde_json::Value) -> Option<Manifest> {
        let mut m = self.get(id)?;
        m.restored = Some(serde_json::json!({ "at": now_iso(), "results": results }));
        fs::write(
            self.dir.join(format!("{id}.json")),
            serde_json::to_string_pretty(&m).ok()?,
        )
        .ok()?;
        Some(m)
    }
}

fn now_secs() -> u64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0)
}

fn now_iso() -> String {
    // Deliberately not pulling a date crate in for two call sites.
    format!("epoch:{}", now_secs())
}

fn now_stamp() -> String {
    format!("{}", now_secs())
}

fn rand_suffix() -> u32 {
    // Enough entropy to avoid a collision within the same second.
    let nanos = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.subsec_nanos())
        .unwrap_or(0);
    nanos & 0xff_ffff
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn split_argv_keeps_quoted_paths_with_spaces_intact() {
        let cmd = r#""C:\Program Files\MetaTrader 5\terminal64.exe" /portable --flag"#;
        assert_eq!(
            split_argv(cmd),
            vec![
                r"C:\Program Files\MetaTrader 5\terminal64.exe",
                "/portable",
                "--flag"
            ]
        );
    }

    #[test]
    fn split_argv_handles_the_real_node_invocation_that_failed_to_restore() {
        let cmd = r#""C:\nvm4w\nodejs\node.exe" "C:\Users\Armyg\App Data\victim.js""#;
        let argv = split_argv(cmd);
        assert_eq!(argv.len(), 2);
        assert_eq!(argv[0], r"C:\nvm4w\nodejs\node.exe");
        assert_eq!(argv[1], r"C:\Users\Armyg\App Data\victim.js");
    }

    #[test]
    fn split_argv_handles_unquoted_commands() {
        assert_eq!(split_argv("ollama serve"), vec!["ollama", "serve"]);
    }

    #[test]
    fn conhost_is_never_restorable() {
        assert!(!is_restorable(
            "conhost.exe",
            &Some(r"C:\Windows\system32\conhost.exe".into()),
            &Some(r"\??\C:\Windows\system32\conhost.exe 0x4".into())
        ));
    }

    #[test]
    fn nt_namespace_command_lines_are_rejected_regardless_of_name() {
        assert!(!is_restorable("weird.exe", &None, &Some(r"\??\C:\x\weird.exe 0x1".into())));
    }

    #[test]
    fn a_normal_process_with_a_path_is_restorable() {
        assert!(is_restorable(
            "node.exe",
            &Some(r"C:\nvm4w\nodejs\node.exe".into()),
            &Some(r#""C:\nvm4w\nodejs\node.exe" server.js"#.into())
        ));
    }

    #[test]
    fn a_process_with_no_path_and_no_cmd_is_not_restorable() {
        assert!(!is_restorable("ghost.exe", &None, &None));
    }

    #[test]
    fn manifests_round_trip_through_disk_with_the_action_intact() {
        let dir = std::env::temp_dir().join(format!("hangar-mtest-{}", rand_suffix()));
        let store = Store::new(&dir);
        let action = Action {
            op: "move-file".into(),
            from: Some(r"C:\Startup\TikTok.lnk".into()),
            to: Some(r"quarantine\startup\TikTok.lnk".into()),
            summary: "Move TikTok.lnk out of Startup into quarantine".into(),
            ..Default::default()
        };
        let v = Victim {
            pid: None,
            name: "startup-folder::x::TikTok".into(),
            mem_mb: None,
            cmd: Some(action.summary.clone()),
            path: None,
            ports: vec![],
            persistence: Some(action.clone()),
            restorable: true,
        };
        let m = store.write("persist-disable", vec![v], serde_json::json!({})).unwrap();

        // The bug this guards: the action block being dropped on write, leaving
        // only prose and an undo button that cannot work.
        let back = store.get(&m.id).expect("manifest readable");
        let p = back.victims[0].persistence.as_ref().expect("action preserved");
        assert_eq!(p.op, "move-file");
        assert_eq!(p.from.as_deref(), Some(r"C:\Startup\TikTok.lnk"));

        assert!(store.list().iter().any(|x| x.id == m.id));
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn a_path_shaped_id_is_rejected() {
        let store = Store::new(std::env::temp_dir());
        assert!(store.get("../../etc/passwd").is_none());
        assert!(store.get("a/b").is_none());
    }
}
